name: pre_work
on:  
  push:
  pull_request:
    branches:
      - main


jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:

      - name: checkout repo content
      - uses: actions/checkout@v2 # checkout the repository content to github runner
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: pip install -r requirements.txt
             python pre_work_train.py
          
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data visulaization" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          cml-send-comment report.md
